name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main # Altere para o nome da branch que deseja usar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20' # Altere para a versão que você precisa

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
